package post

import (
	"fmt"
	"strings"

	"github.com/dimension/ai-ci-agent/internal/provider"
)

// ReviewComment is one inline comment to attach to a GitHub pull request
// review -- Path/Line reference the diff's new-file side, matching what
// assess.ValidateAnchor already verified before Anchored was set true.
type ReviewComment struct {
	Path string
	Line int
	Body string
}

// severityBucket collapses the five-level P0..nit severity scale down to
// the three tiers the report groups and counts by: P0/P1 (the mandatory
// ci-failure diagnosis is always at least P1; P0 is reserved for a
// security-relevant break) are "critical", P2/P3 are "warning", nit is
// "nit".
func severityBucket(severity string) string {
	switch severity {
	case "P0", "P1":
		return "critical"
	case "P2", "P3":
		return "warning"
	default: // "nit", or anything unrecognized
		return "nit"
	}
}

// RenderAssessmentReview builds the top-level summary and inline comments
// for a successful CI-failure diagnosis run, formatted as a structured
// assessment report (Executive Summary / Diagnosis / Additional Findings
// / Recommendation) rather than a flat bullet list. Findings render as
// reflowable prose blocks rather than a markdown table: GitHub's table
// layout doesn't adapt to a narrow viewport (mobile, a sidebar diff
// panel) and forces long headers/cells to wrap character-by-character
// once the column is too narrow to fit a whole word. The mandatory
// ci-failure finding drives the Diagnosis section -- it's the run's own
// diagnosis of why the build broke, not a location-specific finding --
// while any additional findings become inline comments when anchored, or
// a numbered block otherwise. staleHeadSHA disables every inline comment
// (§6.3: an anchor computed against a diff that's no longer the PR's
// head can't be trusted to land on the right line), folding everything
// into the findings list instead.
func RenderAssessmentReview(findings []provider.Assessment, reviewedSHA, staleHeadSHA string) (string, []ReviewComment) {
	var b strings.Builder
	b.WriteString("## AI CI Agent — Assessment Report\n\n")

	stale := staleHeadSHA != ""
	if stale {
		fmt.Fprintf(&b, "> **Note:** this PR's head moved after context was gathered (reviewed `%s`, current head `%s`). Every finding below is shown without an inline anchor.\n\n",
			short(reviewedSHA), short(staleHeadSHA))
	}

	primary, rest := extractPrimary(findings, "ci-failure")
	list, comments, counts := renderFindingsList(rest, !stale)

	riskFindings := rest
	if primary != nil {
		riskFindings = append([]provider.Assessment{*primary}, rest...)
	}
	_, riskLabel := OverallImpact(riskFindings)

	fmt.Fprintf(&b, "### Executive Summary\n\n%s\n\n", executiveSummary(primary, rest, counts))

	if primary != nil {
		b.WriteString("### Diagnosis\n\n")
		fmt.Fprintf(&b, "- **Severity:** %s\n- **Confidence:** %s\n- **Category:** %s\n\n",
			primary.Severity, titleCase(primary.Confidence), primary.Category)
		fmt.Fprintf(&b, "%s\n\n", orNone(primary.Comment))
		if strings.TrimSpace(primary.SuggestedFix) != "" {
			fmt.Fprintf(&b, "**Suggested fix:** %s\n\n", primary.SuggestedFix)
		}
	}

	if list != "" {
		fmt.Fprintf(&b, "### Additional Findings\n\n%s\n", list)
	}

	fmt.Fprintf(&b, "### Recommendation\n\n%s\n\n", recommendation(riskLabel))

	b.WriteString(marker(reviewedSHA))
	return b.String(), comments
}

// RenderReviewReview is RenderAssessmentReview's counterpart for the plain
// PR-review path: no mandatory primary finding, and an empty Findings
// slice is a valid, common "no issues found" outcome. Leads with
// result.Summary (the PR's own description, generated by the same LLM
// call as Findings) as the Executive Summary, then a Risk level and the
// same Findings-list/Recommendation structure as the CI-failure report.
//
// conflicting surfaces GitHub's own merge-conflict signal independent of
// the LLM call: a diff never carries the base branch's current state, so
// the model has no way to see a conflict even if it exists. Checked here
// rather than left to the model means it's never missed.
func RenderReviewReview(result provider.ReviewResult, sha string, conflicting bool) (string, []ReviewComment) {
	var b strings.Builder
	b.WriteString("## AI PR Review — Assessment Report\n\n")

	if conflicting {
		b.WriteString("> **This PR has merge conflicts with its base branch.** GitHub reports it cannot be merged as-is — the review below is based on the diff as submitted.\n\n")
	}

	if summary := strings.TrimSpace(result.Summary); summary != "" {
		fmt.Fprintf(&b, "### Executive Summary\n\n%s\n\n", summary)
	}

	_, riskLabel := OverallImpact(result.Findings)
	fmt.Fprintf(&b, "**Risk level:** %s\n\n", riskLabel)

	if len(result.Findings) == 0 {
		b.WriteString("No issues were identified in this diff.\n\n")
		fmt.Fprintf(&b, "### Recommendation\n\n%s\n\n", recommendation(riskLabel))
		b.WriteString(reviewMarker(sha))
		return b.String(), nil
	}

	list, comments, _ := renderFindingsList(result.Findings, true)
	fmt.Fprintf(&b, "### Findings\n\n%s\n", list)
	fmt.Fprintf(&b, "### Recommendation\n\n%s\n\n", recommendation(riskLabel))
	b.WriteString(reviewMarker(sha))
	return b.String(), comments
}

// OverallImpact buckets a set of findings into a single whole-PR verdict
// -- coarser, and deliberately distinct from severityBucket's per-finding
// bucketing: only a P0 finding earns "Critical" (severityBucket already
// treats P1 as critical too, since the mandatory ci-failure diagnosis is
// always at least P1 and that's a per-finding signal, not a whole-PR
// one); any P1-P3 finding without a P0 present is "Warning"; nit-only or
// zero findings is "Good". Shared by the PR-review report's Risk level,
// the CI-failure report's Recommendation, and the Slack CI-failed card,
// so no surface disagrees about how bad a given run was.
func OverallImpact(findings []provider.Assessment) (emoji, label string) {
	hasP0 := false
	hasOther := false
	for _, f := range findings {
		switch f.Severity {
		case "P0":
			hasP0 = true
		case "P1", "P2", "P3":
			hasOther = true
		}
	}
	switch {
	case hasP0:
		return "🔴", "Critical"
	case hasOther:
		return "🟡", "Warning"
	default:
		return "🟢", "Good"
	}
}

// recommendation turns a whole-PR risk label (from OverallImpact) into
// the report's closing verdict -- the one line meant to answer "can this
// merge as-is."
func recommendation(riskLabel string) string {
	switch riskLabel {
	case "Critical":
		return "**Block merge.** One or more critical-severity findings must be resolved before this change is safe to merge."
	case "Warning":
		return "Review the findings above before merging, or document why they are acceptable to carry forward."
	default:
		return "No blocking issues were identified. This change is clear to proceed through standard review."
	}
}

// executiveSummary is the report's lead paragraph: the outcome plus a
// finding-count headline, meant to stand alone for a reader who never
// scrolls to the findings below.
func executiveSummary(primary *provider.Assessment, rest []provider.Assessment, counts severityCounts) string {
	var b strings.Builder
	if primary != nil {
		fmt.Fprintf(&b, "This run's CI check failed (severity **%s**, %s confidence). ", primary.Severity, titleCase(primary.Confidence))
	} else {
		b.WriteString("This run's CI check failed. ")
	}
	if len(rest) == 0 {
		b.WriteString("No additional issues were identified in this diff.")
	} else {
		fmt.Fprintf(&b, "%d additional finding(s) were identified in this diff (%s).", len(rest), counts.summary())
	}
	return b.String()
}

// extractPrimary pulls the first finding of the given category out of
// findings, returning it separately from the rest. A "" category (or no
// match) is a no-op -- used by the review path, which has no mandatory
// category to pull out.
func extractPrimary(findings []provider.Assessment, category string) (*provider.Assessment, []provider.Assessment) {
	if category == "" {
		return nil, findings
	}
	for i := range findings {
		if findings[i].Category == category {
			primary := findings[i]
			rest := make([]provider.Assessment, 0, len(findings)-1)
			rest = append(rest, findings[:i]...)
			rest = append(rest, findings[i+1:]...)
			return &primary, rest
		}
	}
	return nil, findings
}

type severityCounts struct{ critical, warning, nit int }

// summary renders the counts as plain text, e.g. "1 critical, 2
// warning" -- omitting any tier with a zero count.
func (c severityCounts) summary() string {
	var parts []string
	if c.critical > 0 {
		parts = append(parts, fmt.Sprintf("%d critical", c.critical))
	}
	if c.warning > 0 {
		parts = append(parts, fmt.Sprintf("%d warning", c.warning))
	}
	if c.nit > 0 {
		parts = append(parts, fmt.Sprintf("%d nit", c.nit))
	}
	return strings.Join(parts, ", ")
}

// renderFindingsList turns findings into a numbered sequence of prose
// blocks (deliberately not a markdown table -- see RenderAssessmentReview's
// doc comment for why), the inline PR comments for anchored findings
// (only when allowAnchors is true), and a per-tier count. Returns "" for
// list when findings is empty so callers can skip the section header
// entirely.
func renderFindingsList(findings []provider.Assessment, allowAnchors bool) (list string, comments []ReviewComment, counts severityCounts) {
	if len(findings) == 0 {
		return "", nil, counts
	}

	var b strings.Builder
	for i, f := range findings {
		switch severityBucket(f.Severity) {
		case "critical":
			counts.critical++
		case "warning":
			counts.warning++
		default:
			counts.nit++
		}

		loc := "unanchored"
		switch {
		case f.File != "" && f.Line > 0:
			loc = fmt.Sprintf("`%s:%d`", sanitizeInline(f.File), f.Line)
		case f.File != "":
			loc = fmt.Sprintf("`%s`", sanitizeInline(f.File))
		}

		fmt.Fprintf(&b, "**%d. %s** — %s · %s · %s confidence\n\n%s\n\n",
			i+1, loc, strings.ToUpper(f.Category), f.Severity, titleCase(f.Confidence), orNone(f.Comment))

		if allowAnchors && f.Anchored && f.File != "" {
			comments = append(comments, ReviewComment{Path: f.File, Line: f.Line, Body: inlineCommentBody(f)})
		}
	}
	return strings.TrimRight(b.String(), "\n") + "\n", comments, counts
}

func inlineCommentBody(a provider.Assessment) string {
	var b strings.Builder
	fmt.Fprintf(&b, "**%s — %s (%s confidence)**\n\n", strings.ToUpper(a.Category), a.Severity, titleCase(a.Confidence))
	b.WriteString(orNone(a.Comment))
	if strings.TrimSpace(a.SuggestedFix) != "" {
		fmt.Fprintf(&b, "\n\n**Suggested fix:** %s", a.SuggestedFix)
	}
	return b.String()
}

// RenderReviewFallback is RenderFallback's counterpart for the review
// path -- there's no CI run/raw-logs link to point to here, so the
// message just names the outage. No findings exist in this degrade case,
// so callers pass nil comments alongside this string.
//
// Deliberately embeds no marker: a degraded post is not a completed
// review, so it must never make Post/PostReview's idempotency lookup
// treat this commit as already handled. Without this, one transient
// failure (a rate limit, a provider hiccup) would permanently seal that
// commit against ever getting a real review, even after the root cause
// is fixed -- every later run would just see "already posted" and skip.
// The trade-off is that a persistent failure reposts a fresh fallback
// comment on every retrigger/reconcile sweep instead of going quiet
// after one.
func RenderReviewFallback() string {
	var b strings.Builder
	b.WriteString("## AI PR Review — Assessment Unavailable\n\n")
	b.WriteString("The LLM provider was unavailable or timed out, so no automated review could be generated for this PR.\n\n")
	return b.String()
}

// RenderReviewMinimal is RenderMinimal's counterpart for the review path.
// See RenderReviewFallback for why it embeds no marker.
func RenderReviewMinimal(reason string) string {
	var b strings.Builder
	b.WriteString("## AI PR Review — Assessment Unavailable\n\n")
	fmt.Fprintf(&b, "Unable to produce a full review for this PR: %s\n\n", reason)
	return b.String()
}

// RenderFallback covers §7's "LLM provider unavailable or times out":
// post a fallback review body linking the raw logs and exit non-fatally.
// See RenderReviewFallback for why it embeds no marker.
func RenderFallback(runHTMLURL string) string {
	var b strings.Builder
	b.WriteString("## AI CI Agent — Assessment Unavailable\n\n")
	b.WriteString("The LLM provider was unavailable or timed out, so no automated investigation could be generated for this failure.\n\n")
	if runHTMLURL != "" {
		fmt.Fprintf(&b, "Raw logs: %s\n\n", runHTMLURL)
	}
	return b.String()
}

// RenderMinimal covers the other §7 fallback paths: rate limiting
// exhausted, or the assessment stayed malformed after the bounded repair
// attempt. reason is a short, human-readable explanation. See
// RenderReviewFallback for why it embeds no marker.
func RenderMinimal(reason string) string {
	var b strings.Builder
	b.WriteString("## AI CI Agent — Assessment Unavailable\n\n")
	fmt.Fprintf(&b, "Unable to produce a full investigation for this failure: %s\n\n", reason)
	return b.String()
}

func orNone(s string) string {
	if strings.TrimSpace(s) == "" {
		return "_none provided_"
	}
	return s
}

// sanitizeInline collapses a free-form, LLM-controlled string (only
// File -- Category/Severity/Confidence are enum-validated in
// internal/assess/parse.go) down to a single line for safe placement
// inside a backtick span within a prose sentence: a raw newline there
// would otherwise break the sentence's markdown structure.
func sanitizeInline(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func short(sha string) string {
	if len(sha) > 7 {
		return sha[:7]
	}
	return sha
}
