package post

import (
	"fmt"
	"strings"

	"github.com/dimension/ai-ci-agent/internal/provider"
)

// ReviewComment is one inline comment to attach to a GitHub pull request
// review -- Path/Line reference the diff's new-file side, matching what
// assess.ValidateAnchor already verified before Anchored was set true.
type ReviewComment struct {
	Path string
	Line int
	Body string
}

// severityEmoji buckets the five-level P0..nit severity scale down to a
// three-color signal a reader can triage at a glance: P0/P1 (the
// mandatory ci-failure diagnosis is always at least P1; P0 is reserved
// for a security-relevant break) need attention now, P2/P3 are worth a
// look, nit is take-it-or-leave-it.
func severityEmoji(severity string) string {
	switch severity {
	case "P0", "P1":
		return "🔴"
	case "P2", "P3":
		return "🟡"
	default: // "nit", or anything unrecognized
		return "🟢"
	}
}

// RenderAssessmentReview builds the top-level summary and inline comments
// for a successful CI-failure diagnosis run. The mandatory ci-failure
// finding becomes the summary's lead paragraph -- it's the run's own
// diagnosis of why the build broke, not a location-specific finding --
// while any additional findings become inline comments when anchored, or
// extra summary bullets otherwise. staleHeadSHA disables every inline
// comment (§6.3: an anchor computed against a diff that's no longer the
// PR's head can't be trusted to land on the right line), folding
// everything into the summary instead.
func RenderAssessmentReview(findings []provider.Assessment, reviewedSHA, staleHeadSHA string) (string, []ReviewComment) {
	var b strings.Builder
	b.WriteString("### 🤖 AI CI Agent — review summary\n\n")

	stale := staleHeadSHA != ""
	if stale {
		fmt.Fprintf(&b, "> **Note:** this PR's head moved after context was gathered (reviewed `%s`, current head `%s`). Every finding below is shown without an inline anchor.\n\n",
			short(reviewedSHA), short(staleHeadSHA))
	}

	primary, rest := extractPrimary(findings, "ci-failure")
	if primary != nil {
		fmt.Fprintf(&b, "**Diagnosis:** %s %s · %s confidence\n\n%s\n\n",
			severityEmoji(primary.Severity), primary.Severity, primary.Confidence, orNone(primary.Comment))
		if strings.TrimSpace(primary.SuggestedFix) != "" {
			fmt.Fprintf(&b, "**Suggested fix:** %s\n\n", primary.SuggestedFix)
		}
	}

	bullets, comments, counts := bucketFindings(rest, !stale)
	if len(rest) > 0 {
		fmt.Fprintf(&b, "%s\n\n", counts.line())
		for _, bullet := range bullets {
			fmt.Fprintf(&b, "- %s\n", bullet)
		}
		b.WriteString("\n")
	}

	b.WriteString(marker(reviewedSHA))
	return b.String(), comments
}

// RenderReviewReview is RenderAssessmentReview's counterpart for the plain
// PR-review path: no mandatory primary finding, and an empty Findings
// slice is a valid, common "no issues found" outcome. Leads with
// result.Summary (the PR's own description, generated by the same LLM
// call as Findings) and an Overall impact verdict before the existing
// severity-count + findings-list structure, unchanged below that point.
func RenderReviewReview(result provider.ReviewResult, sha string) (string, []ReviewComment) {
	var b strings.Builder
	b.WriteString("### 🤖 AI PR Review\n\n")

	if summary := strings.TrimSpace(result.Summary); summary != "" {
		fmt.Fprintf(&b, "## Summary\n%s\n\n", summary)
	}
	emoji, label := OverallImpact(result.Findings)
	fmt.Fprintf(&b, "**Overall impact:** %s %s\n\n---\n\n", emoji, label)

	if len(result.Findings) == 0 {
		b.WriteString("✅ No issues found in this diff.\n\n")
		b.WriteString(reviewMarker(sha))
		return b.String(), nil
	}

	bullets, comments, counts := bucketFindings(result.Findings, true)
	fmt.Fprintf(&b, "%s\n\n", counts.line())
	for _, bullet := range bullets {
		fmt.Fprintf(&b, "- %s\n", bullet)
	}
	b.WriteString("\n")
	b.WriteString(reviewMarker(sha))
	return b.String(), comments
}

// OverallImpact buckets a set of findings into a single whole-PR verdict
// -- coarser, and deliberately distinct from severityEmoji's per-finding
// bucketing: only a P0 finding earns 🔴 (severityEmoji already treats P1
// as critical too, since the mandatory ci-failure diagnosis is always at
// least P1 and that's a per-finding signal, not a whole-PR one); any
// P1-P3 finding without a P0 present is 🟡; nit-only or zero findings is
// 🟢. Shared by the PR-review comment's "Overall impact" line and the
// Slack CI-failed card, so the two surfaces never disagree about how bad
// a given run was.
func OverallImpact(findings []provider.Assessment) (emoji, label string) {
	hasP0 := false
	hasOther := false
	for _, f := range findings {
		switch f.Severity {
		case "P0":
			hasP0 = true
		case "P1", "P2", "P3":
			hasOther = true
		}
	}
	switch {
	case hasP0:
		return "🔴", "Critical"
	case hasOther:
		return "🟡", "Warning"
	default:
		return "🟢", "Good"
	}
}

// extractPrimary pulls the first finding of the given category out of
// findings, returning it separately from the rest. A "" category (or no
// match) is a no-op -- used by the review path, which has no mandatory
// category to pull out.
func extractPrimary(findings []provider.Assessment, category string) (*provider.Assessment, []provider.Assessment) {
	if category == "" {
		return nil, findings
	}
	for i := range findings {
		if findings[i].Category == category {
			primary := findings[i]
			rest := make([]provider.Assessment, 0, len(findings)-1)
			rest = append(rest, findings[:i]...)
			rest = append(rest, findings[i+1:]...)
			return &primary, rest
		}
	}
	return nil, findings
}

type severityCounts struct{ critical, warning, nit int }

func (c severityCounts) line() string {
	var parts []string
	if c.critical > 0 {
		parts = append(parts, fmt.Sprintf("🔴 %d critical", c.critical))
	}
	if c.warning > 0 {
		parts = append(parts, fmt.Sprintf("🟡 %d warning", c.warning))
	}
	if c.nit > 0 {
		parts = append(parts, fmt.Sprintf("🟢 %d nit", c.nit))
	}
	return strings.Join(parts, "   ")
}

// bucketFindings splits findings into inline review comments (anchored
// findings, full detail) and summary bullets (everything else: unanchored
// findings, or every finding when allowAnchors is false because the PR's
// head moved since context was gathered).
func bucketFindings(findings []provider.Assessment, allowAnchors bool) (bullets []string, comments []ReviewComment, counts severityCounts) {
	for _, f := range findings {
		emoji := severityEmoji(f.Severity)
		switch emoji {
		case "🔴":
			counts.critical++
		case "🟡":
			counts.warning++
		default:
			counts.nit++
		}

		if allowAnchors && f.Anchored && f.File != "" {
			comments = append(comments, ReviewComment{Path: f.File, Line: f.Line, Body: inlineCommentBody(f, emoji)})
			bullets = append(bullets, fmt.Sprintf("%s `%s:%d` %s — see inline comment", emoji, f.File, f.Line, f.Category))
			continue
		}

		loc := "unanchored"
		if f.File != "" {
			loc = fmt.Sprintf("`%s`", f.File)
		}
		bullets = append(bullets, fmt.Sprintf("%s %s (%s) — %s", emoji, f.Category, loc, orNone(f.Comment)))
	}
	return
}

func inlineCommentBody(a provider.Assessment, emoji string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s **%s** · %s · %s confidence\n\n", emoji, a.Category, a.Severity, a.Confidence)
	b.WriteString(orNone(a.Comment))
	if strings.TrimSpace(a.SuggestedFix) != "" {
		fmt.Fprintf(&b, "\n\n**Suggested fix:** %s", a.SuggestedFix)
	}
	return b.String()
}

// RenderReviewFallback is RenderFallback's counterpart for the review
// path -- there's no CI run/raw-logs link to point to here, so the
// message just names the outage. No findings exist in this degrade case,
// so callers pass nil comments alongside this string.
//
// Deliberately embeds no marker: a degraded post is not a completed
// review, so it must never make Post/PostReview's idempotency lookup
// treat this commit as already handled. Without this, one transient
// failure (a rate limit, a provider hiccup) would permanently seal that
// commit against ever getting a real review, even after the root cause
// is fixed -- every later run would just see "already posted" and skip.
// The trade-off is that a persistent failure reposts a fresh fallback
// comment on every retrigger/reconcile sweep instead of going quiet
// after one.
func RenderReviewFallback() string {
	var b strings.Builder
	b.WriteString("### 🤖 AI PR Review\n\n")
	b.WriteString("The LLM provider was unavailable or timed out, so no automated review could be generated for this PR.\n\n")
	return b.String()
}

// RenderReviewMinimal is RenderMinimal's counterpart for the review path.
// See RenderReviewFallback for why it embeds no marker.
func RenderReviewMinimal(reason string) string {
	var b strings.Builder
	b.WriteString("### 🤖 AI PR Review\n\n")
	fmt.Fprintf(&b, "Unable to produce a full review for this PR: %s\n\n", reason)
	return b.String()
}

// RenderFallback covers §7's "LLM provider unavailable or times out":
// post a fallback review body linking the raw logs and exit non-fatally.
// See RenderReviewFallback for why it embeds no marker.
func RenderFallback(runHTMLURL string) string {
	var b strings.Builder
	b.WriteString("### 🤖 AI CI Agent\n\n")
	b.WriteString("The LLM provider was unavailable or timed out, so no automated investigation could be generated for this failure.\n\n")
	if runHTMLURL != "" {
		fmt.Fprintf(&b, "Raw logs: %s\n\n", runHTMLURL)
	}
	return b.String()
}

// RenderMinimal covers the other §7 fallback paths: rate limiting
// exhausted, or the assessment stayed malformed after the bounded repair
// attempt. reason is a short, human-readable explanation. See
// RenderReviewFallback for why it embeds no marker.
func RenderMinimal(reason string) string {
	var b strings.Builder
	b.WriteString("### 🤖 AI CI Agent\n\n")
	fmt.Fprintf(&b, "Unable to produce a full investigation for this failure: %s\n\n", reason)
	return b.String()
}

func orNone(s string) string {
	if strings.TrimSpace(s) == "" {
		return "_none provided_"
	}
	return s
}

func short(sha string) string {
	if len(sha) > 7 {
		return sha[:7]
	}
	return sha
}
